CineviewsApp/Controllers/FilmesController.cs
using CineviewsApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CineviewsApp.Controllers
{
    [Authorize]
    public class FilmesController : Controller
    {
        private readonly AppDbContext _context;

        public FilmesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DirectorSortParm"] = sortOrder == "Director" ? "director_desc" : "Director";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["ScoreSortParm"] = sortOrder == "Score" ? "score_desc" : "Score";

            var filmes = _context.Filmes.Where(f =>
                EF.Functions.Like(f.Nome, $"%{searchString}%") || EF.Functions.Like(f.Diretor, $"%{searchString}%"));

            switch (sortOrder)
            {
                case "name_desc":
                    filmes = filmes.OrderByDescending(f => f.Nome);
                    break;
                case "Director":
                    filmes = filmes.OrderBy(f => f.Diretor);
                    break;
                case "director_desc":
                    filmes = filmes.OrderByDescending(f => f.Diretor);
                    break;
                case "Date":
                    filmes = filmes.OrderBy(f => f.DataLancamento);
                    break;
                case "date_desc":
                    filmes = filmes.OrderByDescending(f => f.DataLancamento);
                    break;
                case "Score":
                    filmes = filmes.OrderBy(f => f.Score);
                    break;
                case "score_desc":
                    filmes = filmes.OrderByDescending(f => f.Score);
                    break;
                default:
                    filmes = filmes.OrderBy(f => f.Nome);
                    break;
            }

            return View(await filmes.ToListAsync());
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Filme filme)
        {

            if (ModelState.IsValid)
            {
                _context.Filmes.Add(filme);
                 await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(filme);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
                return NotFound();

            var dados = await _context.Filmes.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Filme filme)
        {

            if (id != filme.Id)
                return NotFound();

            if (ModelState.IsValid)
            {

                _context.Filmes.Update(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Filmes.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Filmes.FindAsync(id);

            if (dados == null)
                return NotFound();

            return View(dados);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var dados = await _context.Filmes.FindAsync(id);

            if (dados == null)
                return NotFound();

            _context.Filmes.Remove(dados);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Relatorio(int? id)
        {
            if (id == null)
                return NotFound();

            var filme = await _context.Filmes.FindAsync(id);

            if (filme == null)
                return NotFound();

            var meusfilmes = await _context.Meufilmes.Where(c => c.FilmeId == id).OrderByDescending(c => c.MeuScore).ToListAsync();

            ViewBag.Filme = filme;
            ViewBag.Meusfilmes = meusfilmes;

            return View(meusfilmes);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAssistidoStatus(int id, bool isChecked)
        {
            var filme = await _context.Filmes.FindAsync(id);

            if (filme == null)
            {
                return NotFound();
            }

            filme.IsAssistido = isChecked;
            await _context.SaveChangesAsync();

            return Json(new { success = true });
        }

        public IActionResult Search(string searchString)
        {
            // Retrieve your list of filmes from the database
            var filmes = _context.Filmes
                .Where(f => EF.Functions.Like(f.Nome, $"%{searchString}%") || EF.Functions.Like(f.Diretor, $"%{searchString}%"))
                .ToList();

            return View("Index", filmes);
        }

    }
}

CineviewsApp/Controllers/MeusfilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CineviewsApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace CineviewsApp.Controllers
{
    [Authorize]
    public class MeusfilmesController : Controller
    {
        private readonly AppDbContext _context;

        public MeusfilmesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Meusfilmes
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Meufilmes.Include(m => m.Filme);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Meusfilmes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Meufilmes == null)
            {
                return NotFound();
            }

            var meufilme = await _context.Meufilmes
                .Include(m => m.Filme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meufilme == null)
            {
                return NotFound();
            }

            return View(meufilme);
        }

        public IActionResult Create()
        {
            // Get only the checked movies
            var checkedFilmes = _context.Filmes.Where(f => f.IsAssistido).ToList();

            // Clear ViewBag to avoid duplication
            ViewBag.CheckedFilmes = null;

            ViewBag.CheckedFilmes = checkedFilmes;
            ViewData["FilmeId"] = new SelectList(checkedFilmes, "Id", "Nome");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MeuScore,FilmeId,Review")] Meufilme meufilme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meufilme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmeId"] = new SelectList(_context.Filmes, "Id", "Nome", meufilme.FilmeId);
            return View(meufilme);
        }

        // GET: Meusfilmes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Meufilmes == null)
            {
                return NotFound();
            }

            var meufilme = await _context.Meufilmes.FindAsync(id);
            if (meufilme == null)
            {
                return NotFound();
            }
            ViewData["FilmeId"] = new SelectList(_context.Filmes, "Id", "Nome", meufilme.FilmeId);
            return View(meufilme);
        }

        // POST: Meusfilmes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MeuScore,FilmeId,Review")] Meufilme meufilme)
        {
            if (id != meufilme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meufilme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeufilmeExists(meufilme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmeId"] = new SelectList(_context.Filmes, "Id", "Nome", meufilme.FilmeId);
            return View(meufilme);
        }

        // GET: Meusfilmes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Meufilmes == null)
            {
                return NotFound();
            }

            var meufilme = await _context.Meufilmes
                .Include(m => m.Filme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (meufilme == null)
            {
                return NotFound();
            }

            return View(meufilme);
        }

        // POST: Meusfilmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Meufilmes == null)
            {
                return Problem("Entity set 'AppDbContext.Meufilmes'  is null.");
            }
            var meufilme = await _context.Meufilmes.FindAsync(id);
            if (meufilme != null)
            {
                _context.Meufilmes.Remove(meufilme);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeufilmeExists(int id)
        {
          return _context.Meufilmes.Any(e => e.Id == id);
        }

        public async Task<IActionResult> LikeReview(int id, bool likeType)
        {
            var meufilme = await _context.Meufilmes.FindAsync(id);

            if (meufilme == null)
            {
                return NotFound();
            }

            if (likeType)
            {
                meufilme.ThumbsUp++;
            }
            else
            {
                meufilme.ThumbsDown++;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id });
        }

    }
}

CineviewsApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cineviews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CineviewsApp.styles.css" asp-append-version="true" />
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3 mt-0">
            <div class="navmenu container-fluid">

                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="image-sm d-none">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/cineviews-removebg-preview.png" class="nav-logo" />
                        </a>
                    </div>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="image-sm">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/cineviews-removebg-preview.png" class="nav-logo" /></a>
                    </div>
                }
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-evenly">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Filmes" asp-action="Index">Filmes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Meusfilmes" asp-action="Index">Meus Filmes</a>
                            </li>
                        }


                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-action="Search" asp-controller="Filmes" method="get" class="d-flex" role="search">
                                    <input class="form-control me-2" type="search" placeholder="Buscar Filme" aria-label="Search" name="searchString">
                                    <button class="btn btn-outline-light" type="submit">Search</button>
                                </form>
                            </li>
                        }

                    </ul>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="navbar-nav mt-3 mode">
                            <div class="row">
                                <div class="col p-0">
                                    <p style="font-size: 22px" class="">&#9790</p>
                                </div>
                                <div class="col p-0">
                                    <div class="form-check form-switch m-1">
                                        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" checked>
                                        <label class="form-check-label" for="flexSwitchCheckChecked"></label>
                                    </div>
                                </div>
                                <div class="col p-0">
                                    <p style="font-size: 22px" class="">&#9788</p>
                                </div>
                            </div>
                        </div>
                    }

                    <ul class="navbar-nav m-3">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item p-2 text-success">
                                @User.Identity.Name 
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
@*                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
                            </li> *@
                        }

                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CineviewsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <link rel="stylesheet" href="~/css/Login.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>